# Keys
title = "My TOML Config"

# Datasets
[[Q]]
[Q.urls]
gdp_expenditure = "https://www.ons.gov.uk/economy/grossdomesticproductgdp/datasets/realtimedatabaseforukgdpcomponentsfortheexpenditureapproachtothemeasureofgdp"
gdp_income = "https://www.ons.gov.uk/economy/grossdomesticproductgdp/datasets/realtimedatabaseforukgdpcomponentsfortheincomeapproachtothemeasureofgdp"
business_inv = "https://www.ons.gov.uk/economy/grossdomesticproductgdp/datasets/businessinvestmentrealtimedatabase"

[[M]]
[M.urls]
cla08 = "https://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/outofworkbenefits/datasets/claimantcountrevisionstrianglecla02"
unem04 = "https://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/datasets/unemploymentraterevisionstriangleunem04"


[[triangles]]
[triangles.urls]
gdp_cvm = "https://www.ons.gov.uk/economy/grossdomesticproductgdp/datasets/revisionstrianglesforukgdpabmi"